aced!"
name: Buy Tacos and Pepsi (Mock)

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  reward:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Buy Tacos and Pepsi
        run: |
          echo "Forge success! Buying al pastor tacos & Pepsi Zero for Commander Marco (mock order)."
          echo "Tacos: 3 al pastor, Pepsi Zero, delivery to Cañon City, CO 81212. 🌮🥤"
